### ISSUE TITLE
Running as system tray application

### ISSUE THREAD

**Issue by ThomDietrich** [msiedlarek/winthing#1]
A nice solution to control a Windows machine via MQTT without the pain of Microsoft. I like it ;) I'll be using it in my smart home solution! Do you have further plans for the project? How would you like to move the running application to the windows system tray?

**Comment by msiedlarek** [comment]
I would like that very much actually. I run winthing through a bat script, as a background service, and it works for me, so I've never had any motivation to make it more sophisticated. I would be happy to see a pull request though. ;)

**Comment by ThomDietrich** [comment]
So on your system the process is just permanently minimized to the task bar? I'll look into a system tray solution if/when I find the time. It's just a nice to have feature...

Btw. ;) https://community.openhab.org/t/windows-pc-remote-control-shutdown/16644/10

**Comment by msiedlarek** [comment]
On my systems it's just running windowless, in background. I have a BAT script in autostart which is basically doing `start javaw -jar winthing.jar`

As for OpenHAB - I've written WinThing specifically for use with OpenHAB, so I'm glad this scenario is working for others as well ;)

**Comment by ThomDietrich** [comment]
You should have advertised it earlier ;) I was looking for an adequate solution for hours :grinning: 
Thanks for the bat idea. Maybe you could add this hint to the README.
I'll not find the time to tinker around in this application the next couple of weeks. If you reconsider doing changes, that would be great! If you do the systray function, I'll write a [tutorial](https://community.openhab.org/t/speedtest-cli-integration/7611/1). What do you say? :D

**Comment by DJBenson** [comment]
I use AlwaysUp (https://www.coretechnologies.com/products/AlwaysUp/) to run Winthing as a Windows service and it mostly works OK (apart from a constant nagging session zero prompt). There are free packages that do the same as AlwaysUp and will happily run Winthing as a background service (which can of course be controlled via the standard Windows service framework (services.msc).

**Comment by msiedlarek** [comment]
Done in #9

**Comment by kubawolanin** [comment]
> EDIT: You can also use the sc.exe command line tool included in most Windows builds to create a service 👍

Thanks, that did the trick. If anyone is looking for a solution to create a service, here's how:

Open a elevated terminal (as an Administrator) and type the following:
```
sc.exe create Winthing binpath= c:\Winthing\winthing-1.4.2.exe type= share start= auto
```

Result:
![image](https://user-images.githubusercontent.com/2270505/110486704-2f0e4180-80ed-11eb-91e9-fbc6f043b665.png)
