### ISSUE TITLE
Connection crash on special characters

### ISSUE THREAD

**Issue by ThomDietrich** [msiedlarek/winthing#2]
The connection seems to crash every time an unexpected special character is send. Example:

Topic `winthing/system/commands/open`

Publish `notepad.exe` --> Correctly executed
Publish `notepad.ex` --> Correctly handled (`Cannot open URI: notepad.ex`)
Publish `C:\notepad.exe` or `c:/` or `¯\_(ツ)_/¯` --> 

```
23:59:12.841 [MQTT Call: WinThing] ERROR com.fatico.winthing.messaging.Engine - Connection lost.
23:59:12.842 [main] INFO  com.fatico.winthing.messaging.Engine - Trying to reconnect in 5 seconds...
23:59:17.842 [main] INFO  com.fatico.winthing.messaging.Engine - Connecting to tcp://xxx as WinThing...
```

**Comment by msiedlarek** [comment]
Thanks for letting me know about the problem!
1. You were sending invalid JSON. I don't blame you, this wasn't really explained in the README, but [it is now](https://github.com/msiedlarek/winthing#supported-messages).
2. WinThing was simply dropping connection when receiving invalid JSON. This is fixed now in [v1.1.0](https://github.com/msiedlarek/winthing/releases/tag/v1.1.0).!

**Comment by ThomDietrich** [comment]
Nice! Thanks for the quick response. The added note explains everything. (I didn't check the sourcecode and didn't know which/that any syntax is used. ;) )
I didn't test (2.) yet but I'm sure it's working great. Thanks

**Comment by killercorny** [comment]
Usually I didnt dig out old threads, but this one fits my problem.

I also got the following error when trying to publish a run command:
`[MQTT Call: WinThing] ERROR com.fatico.winthing.messaging.Engine - Invalid JSON received for: system/commands/run`
I use OH2 rules to trigger publishing comands:

`publish("openhab", "winthing/system/commands/run", '["calc.exe"]')`
This one works, but not if I want to use a specific path:
`publish("openhab", "winthing/system/commands/run", '["C:\\extraProgramme\\test.bat"]')`

What is wrong? I allready escaped the backslashes...
