### ISSUE TITLE
change winthing in the topic

### ISSUE THREAD

**Issue by cyclemat** [msiedlarek/winthing#20]
cant find any function that I can change the topic

from 
winthing/keyboard/commands/press_keys
to
PC1/keyboard/commands/press_keys
or 
PC2/keyboard/commands/press_keys
can we add a function to make this ?

**Comment by msiedlarek** [comment]
There's an undocumented setting to do this called `prefix`. You can put in `winthing.conf` or in command line as `-Dprefix=PC1`
