### ISSUE TITLE
Documentation: path delimiter

### ISSUE THREAD

**Issue by ThomDietrich** [msiedlarek/winthing#3]
Working: ["notepad.exe"]
Not working: ["C:\Program Files (x86)\Kodi\Kodi.exe"]
Working: ["C:\\\Program Files (x86)\\\Kodi\\\Kodi.exe"]
Working: ["C:/Program Files (x86)/Kodi/Kodi.exe"]

Please correct the README

**Comment by msiedlarek** [comment]
Thanks, fixed.

**Comment by ThomDietrich** [comment]
Great!
