### ISSUE TITLE
Add support for hibernation/standby

### ISSUE THREAD

**Issue by ThomDietrich** [msiedlarek/winthing#4]
As the title says. Would be a great basic addition.

**Comment by DerFetzer** [comment]
Have a look at my pull request #5.

**Comment by ThomDietrich** [comment]
Thanks!! Any other plans?
Closing because of the PR.

**Comment by msiedlarek** [comment]
Thank you for your contribution, @DerFetzer !

**Comment by kintrupf** [comment]
Could you please update the .jar release? The latest version available does not yet include the suspend command :-(
Thanks for this great project!
