### ISSUE TITLE
Publish "winthing/system/online" before suspend or hibernate

### ISSUE THREAD

**Issue by kintrupf** [msiedlarek/winthing#8]
Should'n winthing publish a "winthing/system/online:false" message just before the suspend or hibernate command is executed?
Ideally it would also publish this when the system is suspended by other means than an MQTT command ;-)

And it would be great if it also could publish a "winthing/system/online:true" after resuming from suspend or hibernate.

**Comment by msiedlarek** [comment]
This is done automatically by connection management and MQTT broker: https://github.com/msiedlarek/winthing/blob/4358cdbafcc07c5a3c7ef404e57bbafae9804090/src/main/java/com/fatico/winthing/systems/system/SystemController.java#L25-L40
